### ISSUE TITLE
Issue on OS X El Capitan

### ISSUE THREAD

**Issue by amazingrando** [aquifer/aquifer-git#15]
When I run `aquifer` I get the following error:

```
module.js:339
    throw err;
    ^

Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/randyoest/www/4k/medstat/.aquifer/node_modules/nodegit/lib/nodegit.js:16:12)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

I'm running OS X El Capitan 10.11.2.
node v5.0.0 (npm v3.3.6)

**Comment by fluxsauce** [comment]
Having the same problems.

https://github.com/nodegit/nodegit/issues/811 - says to upgrade from 0.5.0 - https://github.com/nodegit/nodegit/releases - on v0.8.0 - can we upgrade?

Edit - I manually tested it and updating to v0.8.0 didn't have any build errors.

**Comment by chasingmaxwell** [comment]
The workaround for this was added to the README with #16
